name: ci
on: pull_request
jobs:
 linux:
    uses: ChristopherHX/linux-packaging-scripts/.github/workflows/main.yml@main
    with:
      submodule-refs: |-
        [
          {
            "project": "mcpelauncher-ui",
            "path": "mcpelauncher-ui-qt",
            "ref": ${{ tojson(github.sha) }}
          }
        ]
 macOS:
    uses: ChristopherHX/osx-packaging-scripts/.github/workflows/main.yml@main
    with:
      submodule-refs: |-
        [
          {
            "project": "mcpelauncher-ui",
            "path": "mcpelauncher-ui-qt",
            "ref": ${{ tojson(github.sha) }}
          }
        ]
